### ISSUE TITLE
[iOS] Test Implementation of grab orders

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki/tiki-capture-receipt-capacitor#177]
Make sure the implementation of grab orders is working and fix the possibles issues.

**Comment by ricardobrg** [comment]
This is blocked because TIKI Receipt Capacitor is not building due to an error in TIKI SDK Capacitor (see. https://github.com/tiki/tiki-sdk-capacitor/issues/68.

**Comment by ricardobrg** [comment]
#199 duplicate
