### ISSUE TITLE
[Android] Refactor microblink implementation

### ISSUE THREAD

**Issue by Schuler-Gabriel** [tiki/tiki-capture-receipt-capacitor#241]
As a developer
I need to Refactor the microblink implementation
to keep the SDK updated always able to use new microblink features without big changes 

### What it is now
the microblink is implemented using the old documentation.

### What it should be
the SDK should use the new and recommended way to implement microlbink.

### Acceptance criteria
SDK continues working fine using the new implementation way

**Comment by ricardobrg** [comment]
already implemented
